---
language: java

cache:
  directories:
    - $HOME/.m2

stages:
  - name: deploy
    if: tag IS present

jobs:
  include:
    - stage: deploy
      install: skip
      script: skip
      before_deploy:
        - wget https://github.com/AnimatedLEDStrip/device-pi/raw/master/src/main/resources/rpi-ws281x-java-2.0.0-SNAPSHOT.jar
        - mvn install:install-file -Dfile=rpi-ws281x-java-2.0.0-SNAPSHOT.jar -DgroupId=com.github.mbelling -DartifactId=rpi-ws281x-java -Dversion=2.0.0-SNAPSHOT -Dpackaging=jar -DgeneratePom=true
        - VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout 2> /dev/null)
      deploy:
        - provider: script
          script: mvn package -B
          on:
            tags: true
        - provider: releases
          api_key: $GITHUB_TOKEN
          file: target/animatedledstrip-server-pi-${VERSION}.jar
          skip_cleanup: true
          overwrite: true
          on:
            tags: true
    - stage: deploy
      install: skip
      script: skip
      before_deploy:
        - git clone https://github.com/AnimatedLEDStrip/animatedledstrip.github.io.git
        - cd animatedledstrip.github.io
        - cp ../install-pi-server.sh .
        - git add install-pi-server.sh
        - git commit -m "Update install-pi-server.sh"
      deploy:
        - provider: script
          script:  git push -u https://maxnz:$GITHUB_TOKEN@github.com/AnimatedLEDStrip/animatedledstrip.github.io.git master
          skip_cleanup: true
          on:
            tags: true
