- hosts: localhost
  become: yes
  tasks:
  - name: Increase SPI buff size
    lineinfile:
      path: /boot/cmdline.txt
      line: spidev.bufsiz=32768

  - name: Change GPU Core Frequency
    lineinfile:
      path: /boot/config.txt
      line: core_freq=250


  - name: Install maven
    apt:
      name: maven

  - name: Make /usr/local/src/animatedledstrip directory
    file:
      path: /usr/local/src/animatedledstrip
      state: directory
      mode: '0777'

  - name: Clone Pi Server
    git:
      repo: https://github.com/AnimatedLEDStrip/AnimatedLEDStripPiServerExample.git
      dest: /usr/local/src/animatedledstrip/AnimatedLEDStripPiServerExample

  - name: Clone Pi Device Library
    git:
      repo: https://github.com/AnimatedLEDStrip/AnimatedLEDStripPi.git
      dest: /usr/local/src/animatedledstrip/AnimatedLEDStripPi

  - name: Install dependency jar into maven
    shell: mvn install:install-file -Dfile=/usr/local/src/animatedledstrip/AnimatedLEDStripPi/src/main/resources/rpi-ws281x-java-2.0.0-SNAPSHOT.jar -DgroupId=com.github.mbelling -DartifactId=rpi-ws281x-java -Dversion=2.0.0-SNAPSHOT -Dpackaging=jar -DgeneratePom=true

  - name: Package jar (this will take some time)
    shell: mvn package
    args:
      chdir: /usr/local/src/animatedledstrip/AnimatedLEDStripPiServerExample


  - name: Create /usr/local/leds directory
    file:
      path: /usr/local/leds
      state: directory
      mode: '0777'

  - name: Copy jar
    copy:
      src: /usr/local/src/animatedledstrip/AnimatedLEDStripPiServerExample/target/animatedledstrip-server-example-1.0.jar
      dest: /usr/local/leds/ledserver.jar
      mode: '0777'


  - name: Create /etc/leds directory
    file:
      path: /etc/leds
      state: directory
      mode: '0777'

  - name: Add led.config
    copy:
      src: ansible/led.config
      dest: /etc/leds/led.config
      mode: '0777'


  - name: Add ledserver service
    copy:
      src: ansible/ledserver.service
      dest: /lib/systemd/system/ledserver.service


  - name: Add ledserver.bash
    copy:
      src: ansible/ledserver.bash
      dest: /usr/local/leds/ledserver.bash
      mode: '0777'

  - name: Add ledconsole.bash
    copy:
      src: ansible/ledconsole.bash
      dest: /usr/local/leds/ledconsole.bash
      mode: '0777'

  - name: Add ledupdate.bash
    copy:
      src: ansible/ledupdate.bash
      dest: /usr/local/leds/ledupdate.bash
      mode: '0777'


  - name: Install ledserver
    file:
      src: /usr/local/leds/ledserver.bash
      path: /usr/bin/ledserver
      state: link

  - name: Install ledconsole
    file:
      src: /usr/local/leds/ledconsole.bash
      path: /usr/bin/ledconsole
      state: link

  - name: Install ledupdate
    file:
      src: /usr/local/leds/ledupdate.bash
      path: /usr/bin/ledupdate
      state: link


  - name: Enable ledserver
    shell: systemctl enable ledserver

  - name: Daemon reload
    shell: systemctl daemon-reload

